--liquibase formatted sql

--changeset dev-lite:007-offline-images context:dev-lite
--comment Repoint demo image URLs at the local placeholder endpoint so the seeded world renders with no internet (dev-lite simulator only).

-- The demo seeds reference picsum.photos, which needs egress. dev-lite is the
-- credential-less, network-free simulator profile, so its Liquibase context
-- (spring.liquibase.contexts in application-dev-lite.yml) additionally runs
-- this changeset, swapping those URLs for /api/dev-lite/placeholder/{seed} —
-- deterministic SVGs generated by DevLiteUploadController, no binary assets
-- and no outbound calls. Every other profile keeps the original data.

UPDATE partnership_opportunity_photo
SET url = '/api/dev-lite/placeholder/campaign-' || partnership_opportunity_id || '-' || order_number
WHERE url LIKE '%picsum.photos%';

-- "user" is a reserved word — the table really is quoted everywhere.
UPDATE "user"
SET profile_picture = '/api/dev-lite/placeholder/user-' || id
WHERE profile_picture LIKE '%picsum.photos%';

UPDATE user_social_connection
SET profile_picture_url = '/api/dev-lite/placeholder/social-' || id
WHERE profile_picture_url LIKE '%picsum.photos%';

--rollback UPDATE partnership_opportunity_photo SET url = 'https://picsum.photos/800/600' WHERE url LIKE '/api/dev-lite/placeholder/%';
--rollback UPDATE "user" SET profile_picture = 'https://picsum.photos/400/400' WHERE profile_picture LIKE '/api/dev-lite/placeholder/%';
--rollback UPDATE user_social_connection SET profile_picture_url = 'https://picsum.photos/400/400' WHERE profile_picture_url LIKE '/api/dev-lite/placeholder/%';
