package com.sm.instagram.platform.address;

import com.sm.instagram.platform.common.util.mappers.MappingConfigurer;
import com.sm.instagram.platform.partnershipopportunities.PartnershipOpportunity;
import com.sm.instagram.platform.partnershipopportunities.PartnershipOpportunityRepository;
import com.sm.instagram.platform.user.User;
import com.sm.instagram.platform.user.UserRepository;
import lombok.RequiredArgsConstructor;
import org.modelmapper.Converter;
import org.modelmapper.ModelMapper;
import org.modelmapper.spi.MappingContext;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

/**
 * Configures mappings between Address entities and DTOs.
 */
@Component
@RequiredArgsConstructor
@Order(2)
public class AddressMapping implements MappingConfigurer {

    private final UserRepository userRepository;
    private final PartnershipOpportunityRepository partnershipOpportunityRepository;

    @Override
    public ModelMapper configureMapping(ModelMapper modelMapper) {
        // Entity to DTO mappings
        mapEntityToDto(modelMapper);

        // DTO to Entity mappings
        mapDtoToEntity(modelMapper);
        return modelMapper;
    }

    private void mapEntityToDto(ModelMapper modelMapper) {
        // Map Address to AddressDtoOut
        modelMapper.createTypeMap(Address.class, AddressDtoOut.class)
                .addMappings(mapper ->
                        mapper.using((Converter<Address, Long>) context -> {
                            Address source = context.getSource();
                            return source != null && source.getUser() != null ? source.getUser().getId() : null;
                        }).map(src -> src, AddressDtoOut::setUserId)
                );

        // Map Address to AddressNoUserDtoOut (without userId field)
        modelMapper.createTypeMap(Address.class, AddressNoUserDtoOut.class);

        // Map Address to AddressCityOnlyDto (only city field)
        modelMapper.createTypeMap(Address.class, AddressCityOnlyDto.class);
    }

    private void mapDtoToEntity(ModelMapper modelMapper) {
        // Converter for UserId to User entity
        Converter<Long, User> userIdToUser = ctx ->
                ctx.getSource() == null ? null : userRepository.findById(ctx.getSource()).orElse(null);

        // Converter for PartnershipOpportunityId to PartnershipOpportunity entity
        Converter<Long, PartnershipOpportunity> opportunityIdToOpportunity = ctx ->
                ctx.getSource() == null ? null : partnershipOpportunityRepository.findById(ctx.getSource()).orElse(null);

        // Create a new type map with skipNullEnabled 
        modelMapper.getConfiguration().setSkipNullEnabled(true);

        // Map AddressDtoIn to Address using an empty type map first, then add mappings
        modelMapper.emptyTypeMap(AddressDtoIn.class, Address.class)
                .addMappings(mapper -> {
                    // CRITICAL FIX: Skip id field - it's auto-generated by JPA, not mapped from DTO
                    // This prevents ModelMapper ambiguity when it sees multiple *Id sources:
                    // - AddressDtoIn.getId()
                    // - AddressDtoIn.getUserId()
                    // - AddressDtoIn.getPartnershipOpportunityId()
                    // All matching pattern "*Id" to Address.setId()
                    mapper.skip(Address::setId);

                    mapper.using(userIdToUser).map(AddressDtoIn::getUserId, Address::setUser);
                    mapper.using(opportunityIdToOpportunity)
                            .map(AddressDtoIn::getPartnershipOpportunityId, Address::setPartnershipOpportunity);

                    // Map other fields explicitly
                    mapper.map(AddressDtoIn::getStreet, Address::setStreet);
                    mapper.map(AddressDtoIn::getCity, Address::setCity);
                    mapper.map(AddressDtoIn::getPostalCode, Address::setPostalCode);
                    mapper.map(AddressDtoIn::getCountry, Address::setCountry);
                    mapper.map(AddressDtoIn::getState, Address::setState);
                    mapper.map(AddressDtoIn::getAdditionalInfo, Address::setAdditionalInfo);
                    mapper.map(AddressDtoIn::getAddressType, Address::setAddressType);

                    // Explicitly map isPrimary with a custom converter to ensure the value is preserved
                    mapper.using((Converter<Boolean, Boolean>) MappingContext::getSource)
                            .map(AddressDtoIn::isPrimary, Address::setPrimary);
                });
    }
}