package com.sm.instagram.platform.subscription.entity;

public enum SubscriptionEventType {
    ACCOUNT_ACTIVATED,
    TRIAL_STARTED,
    TRIAL_CANCELLED,
    TRIAL_EXPIRED,
    SUBSCRIPTION_CREATED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_DOWNGRADE_SCHEDULED,
    SUBSCRIPTION_DOWNGRADE_CANCELLED,
    SUBSCRIPTION_DOWNGRADED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    PAYMENT_RECOVERED,
    PAYMENT_EXHAUSTED,
    TERMS_SHOWN,
    TERMS_ACCEPTED,
    GRACE_EXPIRED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_REACTIVATED,
    ACCOUNT_DEACTIVATED
}
