#!/bin/bash
# Docker cleanup script - removes unused images, containers, volumes
# Generated by Ansible - DO NOT EDIT MANUALLY

echo "$(date): Starting Docker cleanup..."

# Remove stopped containers older than 24 hours
docker container prune -f --filter "until=24h"

# Remove unused images older than 7 days
docker image prune -a -f --filter "until=168h"

# Remove unused networks
docker network prune -f

# Display disk usage
echo "$(date): Docker cleanup completed"
df -h /var/lib/docker
