#!/bin/bash
# =============================================================================
# Cloudflare IP Auto-Update Script for Nginx
# Based on best practices from ergin/nginx-cloudflare-real-ip and others
# 
# Purpose: Automatically fetch and update Cloudflare IP ranges in nginx config
# Usage: Run via cron (daily recommended)
# Location: /usr/local/bin/cloudflare-ip-update.sh
# =============================================================================

# Configuration
NGINX_CF_CONFIG="/etc/nginx/conf.d/01-cloudflare.conf"
CF_IPV4_URL="https://www.cloudflare.com/ips-v4"
CF_IPV6_URL="https://www.cloudflare.com/ips-v6"
BACKUP_DIR="/etc/nginx/backups"
LOG_FILE="/var/log/cloudflare-ip-update.log"

# Create necessary directories
mkdir -p "$BACKUP_DIR"

# Simple logging
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

log_message "Starting Cloudflare IP update"

# Backup current config if it exists
if [ -f "$NGINX_CF_CONFIG" ]; then
    BACKUP_FILE="$BACKUP_DIR/01-cloudflare.conf.$(date +%Y%m%d_%H%M%S)"
    cp "$NGINX_CF_CONFIG" "$BACKUP_FILE"
    log_message "Backed up current config to $BACKUP_FILE"
    
    # Keep only last 30 backups
    ls -t "$BACKUP_DIR"/01-cloudflare.conf.* 2>/dev/null | tail -n +31 | xargs -r rm
fi

# Create temporary file
TEMP_FILE="/tmp/cloudflare-ips-$$.conf"

# Write header
cat > "$TEMP_FILE" << 'EOF'
# =============================================================================
# Cloudflare IP Configuration
# Auto-generated by cloudflare-ip-update.sh
EOF
echo "# Last updated: $(date '+%Y-%m-%d %H:%M:%S %Z')" >> "$TEMP_FILE"
cat >> "$TEMP_FILE" << 'EOF'
# =============================================================================

# Cloudflare IP ranges (IPv4)
# Source: https://www.cloudflare.com/ips-v4
EOF

# Fetch and add IPv4 addresses
for ip in $(curl -s -L "$CF_IPV4_URL"); do
    echo "set_real_ip_from $ip;" >> "$TEMP_FILE"
done

# Add IPv6 header
echo "" >> "$TEMP_FILE"
echo "# Cloudflare IP ranges (IPv6)" >> "$TEMP_FILE"
echo "# Source: https://www.cloudflare.com/ips-v6" >> "$TEMP_FILE"

# Fetch and add IPv6 addresses
for ip in $(curl -s -L "$CF_IPV6_URL"); do
    echo "set_real_ip_from $ip;" >> "$TEMP_FILE"
done

# Add footer configuration
cat >> "$TEMP_FILE" << 'EOF'

# Use CF-Connecting-IP header for real IP
real_ip_header CF-Connecting-IP;

# Trust proxies recursively
real_ip_recursive on;

# Map to get real IP from Cloudflare
map $http_cf_connecting_ip $real_ip {
    default $http_cf_connecting_ip;
    "" $remote_addr;
}

# Cloudflare-specific log format
log_format cloudflare '$real_ip - $remote_user [$time_local] '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent" '
                     'CF-Ray: $http_cf_ray CF-Country: $http_cf_ipcountry';

# Map for Cloudflare visitor scheme (HTTP/HTTPS)
map $http_cf_visitor $cf_scheme {
    default $scheme;
    "~*https" https;
    "~*http" http;
}
EOF

# Move new config to final location
mv "$TEMP_FILE" "$NGINX_CF_CONFIG"

# Test nginx configuration
if nginx -t 2>/dev/null; then
    # Reload nginx
    systemctl reload nginx
    log_message "Successfully updated Cloudflare IPs and reloaded nginx"
    
    # Count IPs for logging
    IP_COUNT=$(grep -c "set_real_ip_from" "$NGINX_CF_CONFIG")
    log_message "Total IP ranges configured: $IP_COUNT"
else
    log_message "ERROR: Nginx configuration test failed"
    
    # Restore backup if available
    if [ -n "$BACKUP_FILE" ] && [ -f "$BACKUP_FILE" ]; then
        cp "$BACKUP_FILE" "$NGINX_CF_CONFIG"
        systemctl reload nginx
        log_message "Restored previous configuration from backup"
    fi
    
    exit 1
fi

log_message "Update process completed successfully"
exit 0
