#!/bin/bash
set -euo pipefail

# Script: generate-deployment-env.sh (UPPER_SNAKE_CASE VERSION)
# Purpose: Generate Docker Compose compatible .env file
# FIXED: Now expects UPPER_SNAKE_CASE variables natively

# Default values
OUTPUT_FILE="${OUTPUT_FILE:-.env}"
SPRING_PROFILE="${SPRING_PROFILE:-test}"

# Function to log with timestamp
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >&2
}

# Function to add variable to env file
add_env_var() {
    local key="$1"
    local value="$2"
    # Quote the value if it contains spaces or special characters
    if [[ "$value" =~ [[:space:]] || "$value" =~ [^[:alnum:]_.-] ]]; then
        echo "${key}=\"${value}\"" >> "$OUTPUT_FILE"
    else
        echo "${key}=${value}" >> "$OUTPUT_FILE"
    fi
}

log "Starting environment file generation for ${SPRING_PROFILE} environment"

# Create output directory if it doesn't exist
OUTPUT_DIR="$(dirname "$OUTPUT_FILE")"
if [ ! -d "$OUTPUT_DIR" ]; then
    log "Creating output directory: $OUTPUT_DIR"
    mkdir -p "$OUTPUT_DIR"
fi

# Clear/create output file
> "$OUTPUT_FILE"

# Add header
cat << EOF >> "$OUTPUT_FILE"
# Generated by generate-deployment-env.sh
# Date: $(date)
# Profile: ${SPRING_PROFILE}
# Image: ${IMAGE_TAG}
# GitHub Run: ${GITHUB_RUN_ID:-local}

EOF

# =============================================================================
# CORE DEPLOYMENT VARIABLES
# =============================================================================
add_env_var "ENVIRONMENT" "${ENVIRONMENT:-$SPRING_PROFILE}"
add_env_var "SPRING_PROFILES_ACTIVE" "$SPRING_PROFILE"
add_env_var "IMAGE_TAG" "${IMAGE_TAG}"
add_env_var "BUILD_TIMESTAMP" "${BUILD_TIMESTAMP:-$(date +%s)}"

# =============================================================================
# GITHUB CONTEXT
# =============================================================================
add_env_var "GITHUB_SHA" "${GITHUB_SHA:-local}"
add_env_var "GITHUB_RUN_ID" "${GITHUB_RUN_ID:-0}"
add_env_var "GITHUB_RUN_NUMBER" "${GITHUB_RUN_NUMBER:-0}"
add_env_var "GITHUB_ACTOR" "${GITHUB_ACTOR:-unknown}"
add_env_var "GITHUB_WORKFLOW" "${GITHUB_WORKFLOW:-local}"
add_env_var "CI" "${CI:-false}"
add_env_var "GITHUB_ACTIONS" "${GITHUB_ACTIONS:-false}"

# =============================================================================
# DOCKER IMAGES
# =============================================================================
# Validate GSM_INIT_IMAGE_FULL is set and not using latest
if [ -z "${GSM_INIT_IMAGE_FULL:-}" ]; then
    log "ERROR: GSM_INIT_IMAGE_FULL is not set!"
    exit 1
fi

if [[ "${GSM_INIT_IMAGE_FULL}" == *":latest"* ]]; then
    log "ERROR: GSM_INIT_IMAGE_FULL contains ':latest' tag: ${GSM_INIT_IMAGE_FULL}"
    log "ERROR: A specific version tag is required for security and reproducibility"
    exit 1
fi

log "✓ Using GSM init image: ${GSM_INIT_IMAGE_FULL}"

# Debug: Show exactly what we're writing
log "DEBUG: Writing GSM_INIT_IMAGE=${GSM_INIT_IMAGE_FULL}"
log "DEBUG: Writing GSM_INIT_IMAGE_FULL=${GSM_INIT_IMAGE_FULL}"

add_env_var "MAIN_APP_IMAGE" "${IMAGE_TAG}"
add_env_var "GSM_INIT_IMAGE" "${GSM_INIT_IMAGE_FULL}"
add_env_var "GSM_INIT_IMAGE_FULL" "${GSM_INIT_IMAGE_FULL}"
add_env_var "POSTGRES_IMAGE" "${POSTGRES_IMAGE:-postgres:16.9}"

# =============================================================================
# REGISTRY CONFIGURATION
# =============================================================================
add_env_var "REGISTRY_PRIMARY" "${REGISTRY_PRIMARY}"
add_env_var "DEPLOYMENT_IMAGE_NAME" "${DEPLOYMENT_IMAGE_NAME:-${IMAGE_NAME}}"

# =============================================================================
# CONTAINER CONFIGURATION
# =============================================================================
add_env_var "COMPOSE_PROJECT_NAME" "instagram-platform-${SPRING_PROFILE}"
add_env_var "APP_CONTAINER_NAME" "${APP_CONTAINER_NAME}"
add_env_var "DB_CONTAINER_NAME" "${DB_CONTAINER_NAME}"
add_env_var "CONTAINER_USER_ID" "${CONTAINER_USER_ID:-1000}"
add_env_var "CONTAINER_GROUP_ID" "${CONTAINER_GROUP_ID:-1000}"
add_env_var "CONTAINER_USER_NAME" "${CONTAINER_USER_NAME}"
add_env_var "CONTAINER_GROUP_NAME" "${CONTAINER_GROUP_NAME}"
add_env_var "TARGET_USER" "${CONTAINER_USER_ID:-1000}"
add_env_var "TARGET_GROUP" "${CONTAINER_GROUP_ID:-1000}"

# =============================================================================
# SERVER CONFIGURATION
# =============================================================================
add_env_var "SERVER_PORT" "${SERVER_PORT:-8080}"
add_env_var "CONTEXT_PATH" "${CONTEXT_PATH:-/api}"
add_env_var "ACTUATOR_PATH" "${ACTUATOR_PATH:-/actuator}"
# APP_PORT is deprecated - using SERVER_PORT instead
# Only add APP_PORT if it's set and not "null"
if [ -n "${APP_PORT:-}" ] && [ "${APP_PORT}" != "null" ]; then
    add_env_var "APP_PORT" "${APP_PORT}"
fi
add_env_var "APP_NAME" "instagram-platform-${SPRING_PROFILE}"

# =============================================================================
# DATABASE CONFIGURATION
# =============================================================================
add_env_var "DATABASE_HOST" "${DATABASE_HOST:-postgres}"
add_env_var "DATABASE_NAME" "${DATABASE_NAME}"
add_env_var "DB_PORT" "${DB_PORT:-5432}"

# =============================================================================
# GOOGLE SECRET MANAGER CONFIGURATION
# =============================================================================
add_env_var "GCP_PROJECT_ID" "${GCP_PROJECT_ID:-check-it-out-${SPRING_PROFILE}}"
add_env_var "GSM_SECRETS_PATH" "${GSM_SECRETS_PATH:-/app/config}"
add_env_var "GSM_SECRET_PREFIX" "${GSM_SECRET_PREFIX}"
add_env_var "GOOGLE_APPLICATION_CREDENTIALS" "/var/secrets/gcp-sa/key.json"

# GSM CLI Optimization
add_env_var "GSM_CONFIG_DIR" "/tmp/gsm-config"
add_env_var "XDG_CONFIG_HOME" "/tmp"
add_env_var "XDG_CACHE_HOME" "/tmp"
add_env_var "HOME" "/tmp"

# GSM Timeouts
add_env_var "GSM_INIT_TIMEOUT" "${GSM_INIT_TIMEOUT:-60}"
add_env_var "INIT_RETRY_COUNT" "${INIT_RETRY_COUNT:-5}"
add_env_var "INIT_RETRY_DELAY" "${INIT_RETRY_DELAY:-5}"

# =============================================================================
# PATH CONFIGURATION
# =============================================================================
add_env_var "DEPLOYMENT_PATH" "${DEPLOYMENT_PATH}"
add_env_var "DEPLOYMENT_REMOTE_PATH" "${DEPLOYMENT_PATH}"  # For systemd wrapper compatibility
add_env_var "RUNTIME_PATH" "${RUNTIME_PATH}"
add_env_var "LOG_DIR" "${LOG_BASE_PATH}"
add_env_var "LOG_BASE_PATH" "${LOG_BASE_PATH}"
add_env_var "DOCKER_COMPOSE_FILE" "${DOCKER_COMPOSE_FILE}"
add_env_var "COMPOSE_FILE" "${DEPLOYMENT_PATH}/${DOCKER_COMPOSE_FILE}"  # Full path for systemd wrapper

# =============================================================================
# SYSTEMD & SERVICE CONFIGURATION
# =============================================================================
add_env_var "SYSTEMD_SERVICE_NAME" "${SYSTEMD_SERVICE_NAME}"
add_env_var "STATE_FILE" "${STATE_FILE}"
add_env_var "LOCK_FILE" "${LOCK_FILE}"

# =============================================================================
# TIMEOUT & HEALTH CHECK CONFIGURATION
# =============================================================================
add_env_var "MAX_WAIT_SECONDS" "${MAX_WAIT_SECONDS:-300}"
add_env_var "CHECK_INTERVAL" "${CHECK_INTERVAL:-10}"
add_env_var "SCRIPT_EXECUTION_TIMEOUT_SECONDS" "${SCRIPT_EXECUTION_TIMEOUT_SECONDS:-600}"

# =============================================================================
# DOCKER CONFIGURATION
# =============================================================================
add_env_var "USE_SUDO_DOCKER" "${USE_SUDO_DOCKER:-true}"

# =============================================================================
# CI/CD LOGGING CONFIGURATION
# =============================================================================
add_env_var "CICD_GROUP_NAME" "${CICD_GROUP_NAME:-instagram-cicd}"
add_env_var "CICD_LOG_ENABLED" "${CICD_LOG_ENABLED:-true}"
add_env_var "CICD_LOG_PATH" "${CICD_LOG_PATH:-/var/log/CiCd}"
add_env_var "CICD_LOG_FILE" "${CICD_LOG_FILE:-instagram-platform-cicd.log}"
add_env_var "CICD_LOG_GROUP" "${CICD_LOG_GROUP:-instagram-cicd}"
add_env_var "CICD_LOG_PERMISSIONS" "${CICD_LOG_PERMISSIONS:-0664}"
add_env_var "CICD_LOG_IMMUTABLE" "${CICD_LOG_IMMUTABLE:-true}"
add_env_var "CICD_LOG_ROTATION_ENABLED" "${CICD_LOG_ROTATION_ENABLED:-true}"
add_env_var "CICD_LOG_ROTATION_SIZE" "${CICD_LOG_ROTATION_SIZE:-100M}"
add_env_var "CICD_LOG_ROTATION_COUNT" "${CICD_LOG_ROTATION_COUNT:-10}"
add_env_var "CICD_LOG_ROTATION_COMPRESS" "${CICD_LOG_ROTATION_COMPRESS:-true}"

# =============================================================================
# JVM CONFIGURATION
# =============================================================================
JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0"
JAVA_OPTS="${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom"
add_env_var "JAVA_OPTS" "${JAVA_OPTS}"

# =============================================================================
# DEBUG CONFIGURATION (for test environment)
# =============================================================================
if [ "$SPRING_PROFILE" = "test" ]; then
    add_env_var "GSM_INIT_DEBUG" "true"
else
    add_env_var "GSM_INIT_DEBUG" "false"
fi

# =============================================================================
# VALIDATION
# =============================================================================
log "Validating required environment variables..."

# Required variables that must be set
VALIDATION_ERRORS=0

check_required_var() {
    local display_name="$1"
    local var_name="$2"

    if [ -z "${!var_name:-}" ]; then
        log "ERROR: Missing required variable: $display_name ($var_name)"
        ((VALIDATION_ERRORS++))
    else
        log "✓ Found $display_name: ${!var_name:0:20}..."
    fi
}

# Check all required variables
check_required_var "Image Tag" "IMAGE_TAG"
check_required_var "Server Port" "SERVER_PORT"
check_required_var "Database Name" "DATABASE_NAME"
check_required_var "Container User ID" "CONTAINER_USER_ID"
check_required_var "Container Group ID" "CONTAINER_GROUP_ID"
check_required_var "App Container Name" "APP_CONTAINER_NAME"
check_required_var "DB Container Name" "DB_CONTAINER_NAME"
check_required_var "GCP Project ID" "GCP_PROJECT_ID"
check_required_var "GSM Secret Prefix" "GSM_SECRET_PREFIX"
check_required_var "Deployment Path" "DEPLOYMENT_PATH"
check_required_var "Registry Primary" "REGISTRY_PRIMARY"
check_required_var "Container User Name" "CONTAINER_USER_NAME"
check_required_var "Container Group Name" "CONTAINER_GROUP_NAME"
check_required_var "GSM Init Image Full" "GSM_INIT_IMAGE_FULL"

if [ $VALIDATION_ERRORS -gt 0 ]; then
    log "ERROR: Validation failed with $VALIDATION_ERRORS errors"
    log "ERROR: Make sure all required variables are exported from config loader"
    exit 1
fi

# =============================================================================
# SUMMARY
# =============================================================================
log "Environment file generated successfully: $OUTPUT_FILE"
log "Summary:"
log "  - Profile: $SPRING_PROFILE"
log "  - Image: $IMAGE_TAG"
log "  - Container: $APP_CONTAINER_NAME"
log "  - Database: $DATABASE_NAME"
log "  - GSM Prefix: $GSM_SECRET_PREFIX"
log "  - Deployment Path: $DEPLOYMENT_PATH"
log "  - Total variables: $(grep -c '^[^#]' "$OUTPUT_FILE")"

# Show first few lines for verification (excluding comments)
log "Preview of generated file:"
grep -v '^#' "$OUTPUT_FILE" | head -10 | while read -r line; do
    # Mask sensitive values in preview
    if echo "$line" | grep -qE '(PASSWORD|SECRET|KEY|TOKEN)='; then
        key=$(echo "$line" | cut -d= -f1)
        log "  $key=***masked***"
    else
        log "  $line"
    fi
done

# Final validation - ensure file is not empty
if [ ! -s "$OUTPUT_FILE" ]; then
    log "ERROR: Generated file is empty!"
    exit 1
fi

log "✅ Environment file generation completed successfully"
exit 0