# Monitoring directories creation (Loki stack)

---
- name: Create Loki base directory
  ansible.builtin.file:
    path: "{{ loki_base_path }}"
    state: directory
    owner: "{{ user_loki.name }}"
    group: "{{ user_loki.gid }}"
    mode: "{{ dir_permissions_standard }}"

- name: Create Loki data directory
  ansible.builtin.file:
    path: "{{ loki_data_path }}"
    state: directory
    owner: "{{ user_loki.name }}"
    group: "{{ user_loki.gid }}"
    mode: "{{ dir_permissions_standard }}"

- name: Create Loki rules directory
  ansible.builtin.file:
    path: "{{ loki_base_path }}/rules"
    state: directory
    owner: "{{ user_loki.name }}"
    group: "{{ user_loki.gid }}"
    mode: "{{ dir_permissions_standard }}"

- name: Create Loki secrets directory
  ansible.builtin.file:
    path: "{{ loki_secrets_path }}"
    state: directory
    owner: "{{ user_loki.name }}"
    group: "{{ user_loki.gid }}"
    mode: "{{ dir_permissions_restricted }}"
